### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by suraj21092002** [rakesh-m-r/DBMS-MINI-Project#8]
![16748772992885519290275349650771](https://user-images.githubusercontent.com/121479219/215240450-357d5ac3-39d4-47e3-a5f7-3cce6dbccec9.jpg)
Please reply fast

**Comment by Manojgowda77** [comment]
What’s the problem

**Comment by suraj21092002** [comment]
Bro after login into the page it's showing please try again sometime

**Comment by suraj21092002** [comment]
Please contact me :-9113031486

**Comment by suraj21092002** [comment]
Hlo bro please help me

**Comment by Manojgowda77** [comment]
I had taken this project from someone bro, so I don’t have enough
experience on this.

**Comment by rakesh-m-r** [comment]
Hey looks like problem with sql.php. it trying to get it from the environment change to local variables or add required things to environment variables.


If have followed the the steps mentioned it  works fine.
